import 'package:flutter/material.dart';
import 'package:realitart/core/framework/colors.dart';
import 'package:realitart/core/framework/globals.dart';
import 'package:realitart/presentation/widgets/bottomsheets/filter_bottomsheet.dart';
import 'package:realitart/presentation/widgets/cards/obra_card.dart';
import 'package:realitart/presentation/widgets/screenBase/screen_base.dart';
import 'package:realitart/presentation/widgets/searchBar/searchBar.dart';

class WorksScreen extends StatefulWidget {
  const WorksScreen({Key? key}) : super(key: key);

  @override
  State<WorksScreen> createState() => _WorksScreenState();
}

class _WorksScreenState extends State<WorksScreen> {
  List<ObraCard> lstObras = [];
  List<ObraCard> filteredObras = [];
  List<String> selectFilters = [];
  List<String> filterNames = [];

  TextEditingController _searchController = TextEditingController();

  @override
  void initState() {
    super.initState();
    lstObras = generateobras();
    filteredObras = List.from(lstObras);
    for (var i = 0; i < 10; i++) {
      filterNames.add(generateRandomLoremIpsum(10));
    }
  }

  // Autogenerated list
  List<ObraCard> generateobras() {
    List<ObraCard> lst = [];
    for (var i = 0; i < 10; i++) {
      lst.add(ObraCard(
        imgPath: generateRandomImgUrl(),
        title: generateRandomLoremIpsum(25),
        description: generateRandomLoremIpsum(30),
      ));
    }
    return lst;
  }

  @override
  Widget build(BuildContext context) {
    return ScreenBase(
      body: Column(
        children: [
          Container(
            width: MediaQuery.of(context).size.width * 0.9,
            margin: const EdgeInsets.symmetric(vertical: 10),
            child: const Text('Obras',
                textAlign: TextAlign.left,
                style: TextStyle(
                    fontFamily: 'Gilroy_bold', color: black1, fontSize: 28)),
          ),
          SearchBar(
            searchController: _searchController,
            onSearchTextChanged: _onSearchTextChanged,
            onFilterPressed: _onFilterPressed,
            filtersLen: selectFilters.length.toString(),
          ),
          gridObras(context),
          const SizedBox(
            height: 20,
          ),
        ],
      ),
    );
  }

  Widget gridObras(BuildContext context) {
    return SizedBox(
      width: MediaQuery.of(context).size.width * 0.9,
      height: MediaQuery.of(context).size.height * 0.8,
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          const SizedBox(
            height: 10,
          ),
          SizedBox(
              height: MediaQuery.of(context).size.height * 0.73,
              child: GridView.builder(
                gridDelegate: const SliverGridDelegateWithFixedCrossAxisCount(
                    crossAxisCount: 2, childAspectRatio: 0.66),
                itemCount: filteredObras.length,
                itemBuilder: (BuildContext context, int index) {
                  return filteredObras[index];
                },
              )),
        ],
      ),
    );
  }

  void _onSearchTextChanged(String searchText) {
    setState(() {
      filteredObras = lstObras.where((museo) {
        final title = museo.title.toLowerCase();
        final description = museo.description.toLowerCase();
        final searchLower = searchText.toLowerCase();
        return title.contains(searchLower) || description.contains(searchLower);
      }).toList();
    });
  }

  void _onFilterPressed() {
    showModalBottomSheet(
      context: context,
      isScrollControlled: true,
      clipBehavior: Clip.antiAliasWithSaveLayer,
      shape: const RoundedRectangleBorder(
          borderRadius: BorderRadius.vertical(top: Radius.circular(25.0))),
      builder: (BuildContext context) {
        return FilterBottomSheet(
          filterNames: filterNames,
          selectedFilters: selectFilters,
          onFiltersSelected: (List<String> selectedFilters) {
            //guarda selectedFilters
            setState(() {
              selectFilters = selectedFilters;
            });
            print('selectedFilters: $selectedFilters'
                ' - selectFilters: $selectFilters');
            Navigator.pop(context);
          },
        );
      },
    );
  }
}
